version: '3.8'
services:
  esphome:
    container_name: esphome
    image: esphome/esphome:latest # Используем последний образ ESPHome
    volumes:
      - /udobnidom/esphome/config:/config # Мапируем директорию для конфигураций ESPHome
      - /etc/localtime:/etc/localtime:ro #<---Используем системное время Orange Pi
      - /dev/ttyUSB0:/dev/ttyUSB0 # <-- Раскомментируй, если используешь USB-адаптер для прошивки
      # Добавь другие /dev/ttyUSBx, если у тебя несколько адаптеров
    network_mode: host #<---ВАЖНО: для OTA-обновлений и обнаружения устройств
    env_file:
      - stack.env
    restart: unless-stopped
    privileged: true #<---ВАЖНО: для доступа к USB-портам и полноценной работы в host-сети
