version: "3.9"

services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable-rk
    restart: unless-stopped
    privileged: true
    stop_grace_period: 30s
    shm_size: '2g'
    group_add:
      - "109"
    devices:
      - /dev/dri
      - /dev/dma_heap
      - /dev/rga
      - /dev/mpp_service
      - /dev/video-dec0
      - /dev/video-enc0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /sys/:/sys/:ro
      # Конфиги и настройки → в /udobnidom/frigate/config
      - /udobnidom/frigate/config:/config
      # Записи → в стандартную /media/frigate
      - /media/frigate:/media/frigate
      # Кэш в RAM
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 2147483648 # 2 GB
    ports:
      - "1984:1984"
      - "5000:5000"
      - "1935:1935"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
