version: "3.8"

services:
  wud:
    image: getwud/wud
    container_name: wud
    networks:
      - homeiot_internal
    environment:
      WUD_TRIGGER_MQTT_MOSQUITTO_URL: mqtt://host.docker.internal:1883
      WUD_TRIGGER_MQTT_MOSQUITTO_HASS_ENABLED: "true"
      WUD_TRIGGER_MQTT_MOSQUITTO_HASS_DISCOVERY: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3006:3000"
    restart: unless-stopped

networks:
  homeiot_internal:
    external: true
