version: "3.8"

services:
  wud:
    image: getwud/wud:latest
    container_name: wud
    network_mode: host      # <-- вот этот ключ!
    environment:
      WUD_TRIGGER_MQTT_MOSQUITTO_URL: "mqtt://127.0.0.1:1883"
      WUD_TRIGGER_MQTT_MOSQUITTO_HASS_ENABLED:  "true"
      WUD_TRIGGER_MQTT_MOSQUITTO_HASS_DISCOVERY: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
