version: '3.8'

services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    volumes:
      - /udobnidom/zigbee2mqtt/data:/app/data  # конфиги
      - /run/udev:/run/udev:ro  # доступ к USB
    devices:
      - /dev/ttyUSB0:/dev/ttyACM0  # источник -> цель
    environment:
      - TZ=Europe/Moscow
      - MQTT_SERVER=mqtt://mosquitto
    ports:
      - "8080:8080"
    restart: unless-stopped
    privileged: true
    networks:
      - homeiot_internal
    env_file:
      - stack.env

networks:
  homeiot_internal:
    external: true
